openapi: 3.1.0
info:
  version: 1.0.0
  title: Task API
servers:
  - url: http://localhost:3000
tags:
  - name: Tasks
    description: Task-relation endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
