openapi: 3.1.0
info:
  version: 1.0.0
  title: Task API
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://task-api-zc92.onrender.com
    description: Production server on render
tags:
  - name: Tasks
    description: Task-relation endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
  /tasks/{id}:
    $ref: paths/task.yaml
